### ISSUE TITLE
PHP 8.4 Support

### ISSUE THREAD

**Issue by ejunker** [halaxa/json-machine#116]
The `composer.json` restricts it to `7.0 - 8.3`.  There doesn't seem to be anything in the code that would not be compatible with PHP 8.4

**Comment by ejunker** [comment]
I see the code has been updated for PHP 8.4 but a new release has not been tagged.

**Comment by halaxa** [comment]
The new version with PHP 8.4 support will be released after the stable PHP 8.4 release. I can't make a release with PHP 8.4 support when there's no stable PHP 8.4.

**Comment by norberttech** [comment]
hey @halaxa, PHP 8.4 is out, could you please publish a new release? Thanks!

**Comment by halaxa** [comment]
Hi. The build process depends on the official docker image. The release will be made after it's available.

**Comment by halaxa** [comment]
If you really need it right away, you can depend on `dev-master` or better the latest commit `dev-86fe9c50eff95d1cfd9d3a601e6b36a93c75b80f`

**Comment by norberttech** [comment]
No worries, I wasn't aware that your release cycle depends on docker tags, it's a dependency of [flow-php/flow](https://github.com/flow-php/flow) and the only one that isn't yet supporting 8.4. 
But I appreciate that instead of making a wide composer constraint that would automatically include 8.4 you are waiting to make sure that your lib is compatible with 8.4 💪 
I wish more libs would have a similar approach

**Comment by halaxa** [comment]
Released.
