### ISSUE TITLE
Please add rewind() method.

### ISSUE THREAD

**Issue by PashaShunkow** [halaxa/json-machine#23]
It would be useful when it is necessary to read same file few times.)

**Comment by halaxa** [comment]
Json Machine is not made with rewinding in mind. It is based on generators which themselves are [unrewindable by design](https://www.php.net/manual/en/generator.rewind.php). You MIGHT succeed if you use `JsonMachine::fromStream($yourStreamResource)` and after iteration call `rewind($yourStreamResource)` (file streams are rewindable). But this is **not tested and not meant to be used**.

If you read files, I'd suggest to simply open the file again using `JsonMachine::fromFile()`. There's almost no overhead involved and it will work.
