### ISSUE TITLE
Parser fails with "Syntax error '[' At position N"

### ISSUE THREAD

**Issue by rybakit** [halaxa/json-machine#4]
```php
// works
// $json = '{"result":{"items":[]}}';

// throws the SyntaxError exception because of `"foo":[]`
$json = '{"result":{"foo":[], "items":[]}}'; 

$items = \JsonMachine\JsonMachine::fromString($json, "/result/items");
foreach ($items as $name => $data) {
        echo $data, "\n";
}

```

**Comment by halaxa** [comment]
Thank you very much. Could you please attach a failing test? You can just
add a case to existing parser test dataset.

Dne 10. 1. 2019 1:37 odp. napsal uživatel "Eugene Leonovich" <
notifications@github.com>:

// works// $json = '{"result":{"items":[]}}';// throws the SyntaxError
exception because of `"foo":[]`$json = '{"result":{"foo":[],
"items":[]}}'; $items = \JsonMachine\JsonMachine::fromString($json,
"/result/items");foreach ($items as $name => $data) {        echo
$data, "\n";}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/halaxa/json-machine/issues/4>, or mute the thread

**Comment by rybakit** [comment]
@halaxa Done https://github.com/halaxa/json-machine/pull/5.
